### ISSUE TITLE
Issue with cx_oracle

### ISSUE THREAD

**Issue by Kalavathi2019** [generalPablo/Python-database-connection#1]
I am getting below error.
ModuleNotFoundError: No module named 'cx_Oracle'

Could you please help

**Comment by generalPablo** [comment]
Hi, you should install the cx_Oracle module first. If you are using anaconda python, you can use anaconda prompt. Then type this command "conda install cx_oracle" or "conda install -c anaconda cx_oracle".

If you use pip install, type this in cmd: "pip install cx_Oracle". 
Let me know if you still have issues.

**Comment by Kalavathi2019** [comment]
Hi,
I am using Anaconda and i tried with the above commands but i am getting error.

 File "<ipython-input-2-9a55c93a8335>", line 1
    conda install -c anaconda cx_oracle
                ^
SyntaxError: invalid syntax

Please guide me how to proceed

**Comment by generalPablo** [comment]
You get the error because you typed the command in the python interpreter instead of "anaconda prompt".

Go to start menu and and search anaconda prompt:
![image](https://user-images.githubusercontent.com/47713333/54178818-aaf23680-449f-11e9-9a21-7519056f3469.png)
